Fixed validate env step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,8 +28,8 @@ jobs:
           ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
         run: |
           if [ -z "$ENVIRONMENT_NAME" ]; then
-             echo "$ENVIRONMENT_NAME" secret is missing"
-             exit 1
+            echo "$ENVIRONMENT_NAME" secret is missing"
+            exit 1
           fi
 
           echo "$ENVIRONMENT_NAME" secret is configured"
